### ISSUE TITLE
Update heapster to use kubeconfig credentials on kubernetes

### ISSUE THREAD

**Issue by erictune** [GoogleCloudPlatform/heapster#269]
In the file where you currently create a client using kubernetes_auth file, do something like this:

```go
import (	kclientcmd "github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd" )
...

kubecfg_file          = flag.String("kubecfg_file", "", "Location of kubecfg file for access to kubernetes service")
...

func newKubeClient() (*client.Client, error) {
  var config *client.Config
  if *kubecfg_file != "" {
    var err error
    if config, err = kclientcmd.NewNonInteractiveDeferredLoadingClientConfig(
      &kclientcmd.ClientConfigLoadingRules{ExplicitPath: *kubecfg_file},
      &kclientcmd.ConfigOverrides{}).ClientConfig(); err != nil {
        return nil, err
    }
  } else {
    // however you handle this case
  }
  return client.New(config), nil
}
```

And in your pod template add:
```yaml
volumeMounts:
- name: monitoring-token
  mountPath: /etc/kubernetes/kubeconfig
  readOnly: true
```

and in the heapster container of the pod template add:
```yaml
volumes:
 - name: dns-token
   source:
    secret:
     target:
       kind: Secret
       namespace: default
       name: token-system-monitoring
```

And add this argument to heapster `--kubeconfig=/etc/kubernetes/kubeconfig`
